on:
  workflow_dispatch:

  push:
    branches:
      - main


name: Auto merge

jobs:
  build:
    name: Auto merge main to with-data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source: 'main'
          target: 'with-data'